# Generated by Django 6.0 on 2026-01-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_visit_tests_alter_prescription_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='clinical_notes',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='injury_side',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='injury_type',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='temperature_c',
        ),
        migrations.AddField(
            model_name='vitals',
            name='temperature_f',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
