# Generated by Django 6.0 on 2026-01-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='chronic_conditions',
        ),
    ]
