# Generated by Django 6.0 on 2026-01-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cnic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
